//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HilfsToolFuerTrainerV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HilfsToolfuerTrainerEntities : DbContext
    {
        public HilfsToolfuerTrainerEntities()
            : base("name=HilfsToolfuerTrainerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SpielBericht> SpielBericht { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_Absenzen> T_Absenzen { get; set; }
        public virtual DbSet<T_Anwesenheit> T_Anwesenheit { get; set; }
        public virtual DbSet<T_Bussen> T_Bussen { get; set; }
        public virtual DbSet<T_Event> T_Event { get; set; }
        public virtual DbSet<T_Inventar> T_Inventar { get; set; }
        public virtual DbSet<T_Mannschaft> T_Mannschaft { get; set; }
        public virtual DbSet<T_Spieler> T_Spieler { get; set; }
        public virtual DbSet<T_SpielerAnwesenheit> T_SpielerAnwesenheit { get; set; }
    }
}
