//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HilfsToolFuerTrainerV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Anwesenheit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Anwesenheit()
        {
            this.T_SpielerAnwesenheit = new HashSet<T_SpielerAnwesenheit>();
        }
    
        public int ID { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<bool> istTraining { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SpielerAnwesenheit> T_SpielerAnwesenheit { get; set; }
    }
}
