//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HilfsToolFuerTrainerV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bussen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Bussen()
        {
            this.T_Spieler = new HashSet<T_Spieler>();
        }
    
        public int ID { get; set; }
        public string Grund { get; set; }
        public Nullable<int> Betrag { get; set; }
        public Nullable<bool> istBezahlt { get; set; }
        public Nullable<int> FK_Spieler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Spieler> T_Spieler { get; set; }
        public virtual T_Spieler T_Spieler1 { get; set; }
    }
}
